server:
  port: 8082

spring:
  application:
    name: budget-service
  datasource:
    url: jdbc:mysql://localhost:3306/budget_db
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
