server:
  port: 8084

spring:
  application:
    name: analysis-service
  datasource:
    url: jdbc:mysql://localhost:3306/analysisdb
    username: root
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000