server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: Santa@21

  jpa:
    hibernate:
      ddl-auto: update  # or validate / create / create-drop
    show-sql: true



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    hostname: localhost
    prefer-ip-address: true
