server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: budget-service
          uri: lb://BUDGET-SERVICE
          predicates:
            - Path=/api/budgets/**
        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/api/transactions/**
        - id: analysis-service
          uri: lb://ANALYSIS-SERVICE
          predicates:
            - Path=/api/analysis/**
        - id: report-service
          uri: lb://REPORT-SERVICE
          predicates:
            - Path=/api/reports/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
